name: test-superresassess
on: [pull_request]

env:
  PYTHON_VERSION: "3.10"
  POETRY_VERSION: "1.4.0"
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: |
          pipx install poetry
      - name: Install Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry
          cache-dependency-path: poetry.lock
      - name: setup Poetry environment
        run: |
          poetry env use ${{ env.PYTHON_VERSION }}
      - name: Install the project dependencies
        run: |
          poetry install --no-root
      - name: Run the automated tests
        run: |
          poetry run pytest -vv -m "not slow" --disable-warnings
